### ISSUE TITLE
CA_STORE environment variable

### ISSUE THREAD

**Issue by alexjamesbrown** [aegypius/mkcert-for-nginx-proxy#1]
Unsure what
> You need to set a CA_STORE environment variable according to your distribution :

means...

Is this on the container? or the host?

**Comment by aegypius** [comment]
Hi @alexjamesbrown ! Thanks for your interest !

This `CA_STORE` environment variables should be set in the .env on your host if you use the docker-compose.yml file in the example.

The purpose of this environment variables is to mount a volume to register the root ca certificate in your host certificate store.

Depending on your usage or distribution you may have to change this value to the proper directory.

Best regards.

**Comment by alexjamesbrown** [comment]
Ah, I see...
I'm on Windows (the host) so if I do 

mkcert - CAROOT 

Is this what I need to set as the env variable?

Thanks

**Comment by aegypius** [comment]
I am not sure :thinking:  

I just looked at https://github.com/FiloSottile/mkcert/blob/master/truststore_windows.go and seems that there is a system call to setup root certificate (but I am far from being fluent in golang). 

You may have to reverse the way I intended this container to work by running mkcert locally first (this will setup the certificate authority in the windows system store and the various browsers) and then share the certificate in the CA_STORE volume.

I don't have any Windows computer (or vm) near me for the moment. this is a wild guess !

If you manage to get it working please feel free to open a PR and update the README.md ! 
If not I will try to setup a working windows environment I soon as I manage to find the time !
